name: zupa_na_pietrynie
description: A new Zupa Na Pietrynie project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  posts_repository:
    path: packages/posts_repository
  events_repository:
    path: packages/events_repository
  bloc: ^8.1.0
  equatable: ^2.0.3
  firebase_core: ^2.1.0
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  font_awesome_flutter: ^10.1.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.0
  meta: ^1.7.0
  stream_transform: ^2.0.0
  bloc_concurrency: ^0.2.0
  file_picker: ^5.2.5
  animated_snack_bar: ^0.3.0
  intl: ^0.18.1


dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/

dependency_overrides:
  bloc: ^8.1.0
  bloc_test: ^9.1.0
  flutter_bloc: ^8.1.1